AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket with optional versioning

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket

  EnableVersioning:
    Type: String
    AllowedValues: [Enabled, Suspended]
    Default: Suspended
    Description: Enable versioning (Enabled/Suspended)

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref EnableVersioning
 
